[build]
command = "python zola/convert.py && zola --root $ZOLA_DIR build --output-dir public"
publish = "public"

[build.environment]
LANDING_BUTTON = "Explore"
LANDING_DESCRIPTION = "This is my personal knowledge management system. Concepts and snippets of knowledge are organized in an (unstructure) inter-linked knowledge graph."
LANDING_PAGE = "home"
LANDING_TITLE = "My Second Brain"
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/ppeetteerrs/obsidian-pkm"
SITE_TITLE = "Peter Yuen"
SITE_URL = "https://ihaveocd.netlify.app/"
TIMEZONE = "Asia/Hong_Kong"
ZOLA_DIR = "zola"
ZOLA_VERSION = "0.15.2"
